#ifndef _LIBRECOMPAT_CONFIG_H_
#define _LIBRECOMPAT_CONFIG_H_

#define LIBRECOMPAT_ROOTLESS 1

/* Determine if rootless by target version */
#ifndef LIBRECOMPAT_ROOTLESS
#define LIBRECOMPAT_ROOTLESS (__ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__ && __ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__ >= 150000)
#endif

#endif
